<!--
 * @Description: 文件及简介
 * @Author: Cary
 * @Date: 2019-12-12 11:15:37
 * @FilePath: f:\vue-project\alien-vue-admin\src\views\icons\element-ui-icon.vue
 -->
<template>
  <div class="app-container">
    <el-card>
      <div>
        使用的是 iconfont 批量导入项目中的所有图标. 图标数量: {{ iconList.length }}
      </div>
    </el-card>
    <el-card class="cc-mar-t-10">
      <div class="c-icon-grid">
         <div v-for="icon in iconList" :key="icon.id" class="c-icon-item">
          <svg-icon class="c-icon-tip" :icon-class="icon.icon" />
          <p class="cc-mar-2 cc-f-s14 c-text-subheading65">{{ icon.icon }}</p>
        </div>
      </div>
    </el-card>
  </div>
</template>
<script>

const icons = [
  { id: 'icon_font_01', icon: 'auto' },
  { id: 'icon_font_11', icon: 'all' },
  { id: 'icon_font_21', icon: 'bussiness-man' },
  { id: 'icon_font_31', icon: 'component' },
  { id: 'icon_font_41', icon: 'code' },
  { id: 'icon_font_51', icon: 'copy' },
  { id: 'icon_font_61', icon: 'dollar' },
  { id: 'icon_font_71', icon: 'history' },
  { id: 'icon_font_81', icon: 'editor' },
  { id: 'icon_font_91', icon: 'data' },
  { id: 'icon_font_101', icon: 'gift' },
  { id: 'icon_font_111', icon: 'integral' },
  { id: 'icon_font_121', icon: 'nav-list' },
  { id: 'icon_font_131', icon: 'pic' },
  { id: 'icon_font_141', icon: 'Notvisible' },
  { id: 'icon_font_151', icon: 'play' },
  { id: 'icon_font_161', icon: 'rising' },
  { id: 'icon_font_171', icon: 'QRcode' },
  { id: 'icon_font_181', icon: 'rmb' },
  { id: 'icon_font_191', icon: 'similar-product' },
  { id: 'icon_font_201', icon: 'Exportservices' },
  { id: 'icon_font_211', icon: 'sendinquiry' },
  { id: 'icon_font_221', icon: 'all-fill' },
  { id: 'icon_font_231', icon: 'favorites-fill' },
  { id: 'icon_font_241', icon: 'integral-fill' },
  { id: 'icon_font_251', icon: 'namecard-fill' },
  { id: 'icon_font_261', icon: 'pic-fill' },
  { id: 'icon_font_271', icon: 'play-fill' },
  { id: 'icon_font_281', icon: 'prompt-fill' },
  { id: 'icon_font_291', icon: 'stop-fill' },
  { id: 'icon_font_301', icon: 'column' },
  { id: 'icon_font_311', icon: 'add-account' },
  { id: 'icon_font_321', icon: 'column1' },
  { id: 'icon_font_331', icon: 'add' },
  { id: 'icon_font_341', icon: 'agriculture' },
  { id: 'icon_font_351', icon: 'years' },
  { id: 'icon_font_361', icon: 'add-cart' },
  { id: 'icon_font_371', icon: 'arrow-right' },
  { id: 'icon_font_381', icon: 'arrow-lift' },
  { id: 'icon_font_391', icon: 'apparel' },
  { id: 'icon_font_401', icon: 'all1' },
  { id: 'icon_font_411', icon: 'arrow-up' },
  { id: 'icon_font_421', icon: 'ascending' },
  { id: 'icon_font_431', icon: 'ashbin' },
  { id: 'icon_font_441', icon: 'atm' },
  { id: 'icon_font_451', icon: 'bad' },
  { id: 'icon_font_461', icon: 'attachent' },
  { id: 'icon_font_471', icon: 'browse' },
  { id: 'icon_font_481', icon: 'beauty' },
  { id: 'icon_font_491', icon: 'atm-away' },
  { id: 'icon_font_501', icon: 'assessed-badge' },
  { id: 'icon_font_511', icon: 'auto1' },
  { id: 'icon_font_521', icon: 'bags' },
  { id: 'icon_font_531', icon: 'calendar' },
  { id: 'icon_font_541', icon: 'cart-full' },
  { id: 'icon_font_551', icon: 'calculator' },
  { id: 'icon_font_561', icon: 'cameraswitching' },
  { id: 'icon_font_571', icon: 'cecurity-protection' },
  { id: 'icon_font_581', icon: 'category' },
  { id: 'icon_font_591', icon: 'close' },
  { id: 'icon_font_601', icon: 'certified-supplier' },
  { id: 'icon_font_611', icon: 'cart-Empty' },
  { id: 'icon_font_621', icon: 'code1' },
  { id: 'icon_font_631', icon: 'color' },
  { id: 'icon_font_641', icon: 'conditions' },
  { id: 'icon_font_651', icon: 'confirm' },
  { id: 'icon_font_661', icon: 'company' },
  { id: 'icon_font_671', icon: 'ali-clould' },
  { id: 'icon_font_681', icon: 'copy1' },
  { id: 'icon_font_691', icon: 'credit-level' },
  { id: 'icon_font_701', icon: 'coupons' },
  { id: 'icon_font_711', icon: 'connections' },
  { id: 'icon_font_721', icon: 'cry' },
  { id: 'icon_font_731', icon: 'costoms-alearance' },
  { id: 'icon_font_741', icon: 'clock' },
  { id: 'icon_font_751', icon: 'CurrencyConverter' },
  { id: 'icon_font_761', icon: 'cut' },
  { id: 'icon_font_771', icon: 'data1' },
  { id: 'icon_font_781', icon: 'Customermanagement' },
  { id: 'icon_font_791', icon: 'descending' },
  { id: 'icon_font_801', icon: 'double-arro-right' },
  { id: 'icon_font_811', icon: 'customization' },
  { id: 'icon_font_821', icon: 'double-arrow-left' },
  { id: 'icon_font_831', icon: 'discount' },
  { id: 'icon_font_841', icon: 'download' },
  { id: 'icon_font_851', icon: 'dollar1' },
  { id: 'icon_font_861', icon: 'default-template' },
  { id: 'icon_font_871', icon: 'editor1' },
  { id: 'icon_font_881', icon: 'eletrical' },
  { id: 'icon_font_891', icon: 'electronics' },
  { id: 'icon_font_901', icon: 'etrical-equipm' },
  { id: 'icon_font_911', icon: 'ellipsis' },
  { id: 'icon_font_921', icon: 'email' },
  { id: 'icon_font_931', icon: 'falling' },
  { id: 'icon_font_941', icon: 'earth' },
  { id: 'icon_font_951', icon: 'filter' },
  { id: 'icon_font_961', icon: 'furniture' },
  { id: 'icon_font_971', icon: 'folder' },
  { id: 'icon_font_981', icon: 'feeds' },
  { id: 'icon_font_991', icon: 'history1' },
  { id: 'icon_font_1001', icon: 'hardware' },
  { id: 'icon_font_1011', icon: 'help' },
  { id: 'icon_font_1021', icon: 'good' },
  { id: 'icon_font_1031', icon: 'Householdappliances' },
  { id: 'icon_font_1041', icon: 'gift1' },
  { id: 'icon_font_1051', icon: 'form' },
  { id: 'icon_font_1061', icon: 'image-text' },
  { id: 'icon_font_1071', icon: 'hot' },
  { id: 'icon_font_1081', icon: 'inspection' },
  { id: 'icon_font_1091', icon: 'leftbutton' },
  { id: 'icon_font_1101', icon: 'jewelry' },
  { id: 'icon_font_1111', icon: 'ipad' },
  { id: 'icon_font_1121', icon: 'leftarrow' },
  { id: 'icon_font_1131', icon: 'integral1' },
  { id: 'icon_font_1141', icon: 'kitchen' },
  { id: 'icon_font_1151', icon: 'inquiry-template' },
  { id: 'icon_font_1161', icon: 'link' },
  { id: 'icon_font_1171', icon: 'libra' },
  { id: 'icon_font_1181', icon: 'loading' },
  { id: 'icon_font_1191', icon: 'listing-content' },
  { id: 'icon_font_1201', icon: 'lights' },
  { id: 'icon_font_1211', icon: 'logistics-icon' },
  { id: 'icon_font_1221', icon: 'messagecenter' },
  { id: 'icon_font_1231', icon: 'mobile-phone' },
  { id: 'icon_font_1241', icon: 'manage-order' },
  { id: 'icon_font_1251', icon: 'move' },
  { id: 'icon_font_1261', icon: 'Moneymanagement' },
  { id: 'icon_font_1271', icon: 'namecard' },
  { id: 'icon_font_1281', icon: 'map' },
  { id: 'icon_font_1291', icon: 'Newuserzone' },
  { id: 'icon_font_1301', icon: 'multi-language' },
  { id: 'icon_font_1311', icon: 'office' },
  { id: 'icon_font_1321', icon: 'notice' },
  { id: 'icon_font_1331', icon: 'ontimeshipment' },
  { id: 'icon_font_1341', icon: 'office-supplies' },
  { id: 'icon_font_1351', icon: 'password' },
  { id: 'icon_font_1361', icon: 'Notvisible1' },
  { id: 'icon_font_1371', icon: 'operation' },
  { id: 'icon_font_1381', icon: 'packaging' },
  { id: 'icon_font_1391', icon: 'online-tracking' },
  { id: 'icon_font_1401', icon: 'packing-labeling' },
  { id: 'icon_font_1411', icon: 'phone' },
  { id: 'icon_font_1421', icon: 'pic1' },
  { id: 'icon_font_1431', icon: 'pin' },
  { id: 'icon_font_1441', icon: 'play1' },
  { id: 'icon_font_1451', icon: 'logistic-logo' },
  { id: 'icon_font_1461', icon: 'print' },
  { id: 'icon_font_1471', icon: 'product' },
  { id: 'icon_font_1481', icon: 'machinery' },
  { id: 'icon_font_1491', icon: 'process' },
  { id: 'icon_font_1501', icon: 'prompt' },
  { id: 'icon_font_1511', icon: 'QRcode1' },
  { id: 'icon_font_1521', icon: 'reeor' },
  { id: 'icon_font_1531', icon: 'reduce' },
  { id: 'icon_font_1541', icon: 'Non-staplefood' },
  { id: 'icon_font_1551', icon: 'rejected-order' },
  { id: 'icon_font_1561', icon: 'resonserate' },
  { id: 'icon_font_1571', icon: 'remind' },
  { id: 'icon_font_1581', icon: 'responsetime' },
  { id: 'icon_font_1591', icon: 'return' },
  { id: 'icon_font_1601', icon: 'paylater' },
  { id: 'icon_font_1611', icon: 'rising1' },
  { id: 'icon_font_1621', icon: 'Rightarrow' },
  { id: 'icon_font_1631', icon: 'rmb1' },
  { id: 'icon_font_1641', icon: 'RFQ-logo' },
  { id: 'icon_font_1651', icon: 'save' },
  { id: 'icon_font_1661', icon: 'scanning' },
  { id: 'icon_font_1671', icon: 'security' },
  { id: 'icon_font_1681', icon: 'salescenter' },
  { id: 'icon_font_1691', icon: 'seleted' },
  { id: 'icon_font_1701', icon: 'searchcart' },
  { id: 'icon_font_1711', icon: 'raw' },
  { id: 'icon_font_1721', icon: 'service' },
  { id: 'icon_font_1731', icon: 'share' },
  { id: 'icon_font_1741', icon: 'signboard' },
  { id: 'icon_font_1751', icon: 'shuffling-banner' },
  { id: 'icon_font_1761', icon: 'Rightbutton' },
  { id: 'icon_font_1771', icon: 'sorting' },
  { id: 'icon_font_1781', icon: 'sound-Mute' },
  { id: 'icon_font_1791', icon: 'Similarproducts' },
  { id: 'icon_font_1801', icon: 'sound-filling' },
  { id: 'icon_font_1811', icon: 'suggest' },
  { id: 'icon_font_1821', icon: 'stop' },
  { id: 'icon_font_1831', icon: 'success' },
  { id: 'icon_font_1841', icon: 'supplier-features' },
  { id: 'icon_font_1851', icon: 'switch' },
  { id: 'icon_font_1861', icon: 'survey' },
  { id: 'icon_font_1871', icon: 'template' },
  { id: 'icon_font_1881', icon: 'text' },
  { id: 'icon_font_1891', icon: 'suspended' },
  { id: 'icon_font_1901', icon: 'task-management' },
  { id: 'icon_font_1911', icon: 'tool' },
  { id: 'icon_font_1921', icon: 'Top' },
  { id: 'icon_font_1931', icon: 'smile' },
  { id: 'icon_font_1941', icon: 'textile-products' },
  { id: 'icon_font_1951', icon: 'tradealert' },
  { id: 'icon_font_1961', icon: 'topsales' },
  { id: 'icon_font_1971', icon: 'tradingvolume' },
  { id: 'icon_font_1981', icon: 'training' },
  { id: 'icon_font_1991', icon: 'upload' },
  { id: 'icon_font_2001', icon: 'RFQ-word' },
  { id: 'icon_font_2011', icon: 'viewlarger' },
  { id: 'icon_font_2021', icon: 'viewgallery' },
  { id: 'icon_font_2031', icon: 'vehivles' },
  { id: 'icon_font_2041', icon: 'trust' },
  { id: 'icon_font_2051', icon: 'warning' },
  { id: 'icon_font_2061', icon: 'warehouse' },
  { id: 'icon_font_2071', icon: 'shoes' },
  { id: 'icon_font_2081', icon: 'video' },
  { id: 'icon_font_2091', icon: 'viewlist' },
  { id: 'icon_font_2101', icon: 'set' },
  { id: 'icon_font_2111', icon: 'store' },
  { id: 'icon_font_2121', icon: 'tool-hardware' },
  { id: 'icon_font_2131', icon: 'vs' },
  { id: 'icon_font_2141', icon: 'toy' },
  { id: 'icon_font_2151', icon: 'sport' },
  { id: 'icon_font_2161', icon: 'creditcard' },
  { id: 'icon_font_2171', icon: 'contacts' },
  { id: 'icon_font_2181', icon: 'checkstand' },
  { id: 'icon_font_2191', icon: 'aviation' },
  { id: 'icon_font_2201', icon: 'Daytimemode' },
  { id: 'icon_font_2211', icon: 'infantmom' },
  { id: 'icon_font_2221', icon: 'discounts' },
  { id: 'icon_font_2231', icon: 'invoice' },
  { id: 'icon_font_2241', icon: 'insurance' },
  { id: 'icon_font_2251', icon: 'nightmode' },
  { id: 'icon_font_2261', icon: 'usercenter' },
  { id: 'icon_font_2271', icon: 'unlock' },
  { id: 'icon_font_2281', icon: 'vip' },
  { id: 'icon_font_2291', icon: 'wallet' },
  { id: 'icon_font_2301', icon: 'landtransportation' },
  { id: 'icon_font_2311', icon: 'voice' },
  { id: 'icon_font_2321', icon: 'exchangerate' },
  { id: 'icon_font_2331', icon: 'contacts-fill' },
  { id: 'icon_font_2341', icon: 'add-account1' },
  { id: 'icon_font_2351', icon: 'years-fill' },
  { id: 'icon_font_2361', icon: 'add-cart-fill' },
  { id: 'icon_font_2371', icon: 'add-fill' },
  { id: 'icon_font_2381', icon: 'all-fill1' },
  { id: 'icon_font_2391', icon: 'ashbin-fill' },
  { id: 'icon_font_2401', icon: 'calendar-fill' },
  { id: 'icon_font_2411', icon: 'bad-fill' },
  { id: 'icon_font_2421', icon: 'bussiness-man-fill' },
  { id: 'icon_font_2431', icon: 'atm-fill' },
  { id: 'icon_font_2441', icon: 'cart-full-fill' },
  { id: 'icon_font_2451', icon: 'cart-Empty-fill' },
  { id: 'icon_font_2461', icon: 'cameraswitching-fill' },
  { id: 'icon_font_2471', icon: 'atm-away-fill' },
  { id: 'icon_font_2481', icon: 'certified-supplier-fill' },
  { id: 'icon_font_2491', icon: 'calculator-fill' },
  { id: 'icon_font_2501', icon: 'clock-fill' },
  { id: 'icon_font_2511', icon: 'ali-clould-fill' },
  { id: 'icon_font_2521', icon: 'color-fill' },
  { id: 'icon_font_2531', icon: 'coupons-fill' },
  { id: 'icon_font_2541', icon: 'cecurity-protection-fill' },
  { id: 'icon_font_2551', icon: 'credit-level-fill' },
  { id: 'icon_font_2561', icon: 'default-template-fill' },
  { id: 'icon_font_2571', icon: 'CurrencyConverter-fill' },
  { id: 'icon_font_2581', icon: 'Customermanagement-fill' },
  { id: 'icon_font_2591', icon: 'discounts-fill' },
  { id: 'icon_font_2601', icon: 'Daytimemode-fill' },
  { id: 'icon_font_2611', icon: 'exl-fill' },
  { id: 'icon_font_2621', icon: 'cry-fill' },
  { id: 'icon_font_2631', icon: 'email-fill' },
  { id: 'icon_font_2641', icon: 'filter-fill' },
  { id: 'icon_font_2651', icon: 'folder-fill' },
  { id: 'icon_font_2661', icon: 'feeds-fill' },
  { id: 'icon_font_2671', icon: 'gold-supplie-fill' },
  { id: 'icon_font_2681', icon: 'form-fill' },
  { id: 'icon_font_2691', icon: 'camera-fill' },
  { id: 'icon_font_2701', icon: 'good-fill' },
  { id: 'icon_font_2711', icon: 'image-text-fill' },
  { id: 'icon_font_2721', icon: 'inspection-fill' },
  { id: 'icon_font_2731', icon: 'hot-fill' },
  { id: 'icon_font_2741', icon: 'company-fill' },
  { id: 'icon_font_2751', icon: 'discount-fill' },
  { id: 'icon_font_2761', icon: 'insurance-fill' },
  { id: 'icon_font_2771', icon: 'inquiry-template-fill' },
  { id: 'icon_font_2781', icon: 'leftbutton-fill' },
  { id: 'icon_font_2791', icon: 'integral-fill1' },
  { id: 'icon_font_2801', icon: 'help1' },
  { id: 'icon_font_2811', icon: 'listing-content-fill' },
  { id: 'icon_font_2821', icon: 'logistic-logo-fill' },
  { id: 'icon_font_2831', icon: 'Moneymanagement-fill' },
  { id: 'icon_font_2841', icon: 'manage-order-fill' },
  { id: 'icon_font_2851', icon: 'multi-language-fill' },
  { id: 'icon_font_2861', icon: 'logistics-icon-fill' },
  { id: 'icon_font_2871', icon: 'Newuserzone-fill' },
  { id: 'icon_font_2881', icon: 'nightmode-fill' },
  { id: 'icon_font_2891', icon: 'office-supplies-fill' },
  { id: 'icon_font_2901', icon: 'notice-fill' },
  { id: 'icon_font_2911', icon: 'mute' },
  { id: 'icon_font_2921', icon: 'order-fill' },
  { id: 'icon_font_2931', icon: 'password1' },
  { id: 'icon_font_2941', icon: 'map1' },
  { id: 'icon_font_2951', icon: 'paylater-fill' },
  { id: 'icon_font_2961', icon: 'phone-fill' },
  { id: 'icon_font_2971', icon: 'online-tracking-fill' },
  { id: 'icon_font_2981', icon: 'play-fill1' },
  { id: 'icon_font_2991', icon: 'pdf-fill' },
  { id: 'icon_font_3001', icon: 'phone1' },
  { id: 'icon_font_3011', icon: 'pin-fill' },
  { id: 'icon_font_3021', icon: 'product-fill' },
  { id: 'icon_font_3031', icon: 'rankinglist-fill' },
  { id: 'icon_font_3041', icon: 'reduce-fill' },
  { id: 'icon_font_3051', icon: 'reeor-fill' },
  { id: 'icon_font_3061', icon: 'pic-fill1' },
  { id: 'icon_font_3071', icon: 'rankinglist' },
  { id: 'icon_font_3081', icon: 'product1' },
  { id: 'icon_font_3091', icon: 'prompt-fill1' },
  { id: 'icon_font_3101', icon: 'resonserate-fill' },
  { id: 'icon_font_3111', icon: 'remind-fill' },
  { id: 'icon_font_3121', icon: 'Rightbutton-fill' },
  { id: 'icon_font_3131', icon: 'RFQ-logo-fill' },
  { id: 'icon_font_3141', icon: 'RFQ-word-fill' },
  { id: 'icon_font_3151', icon: 'searchcart-fill' },
  { id: 'icon_font_3161', icon: 'salescenter-fill' },
  { id: 'icon_font_3171', icon: 'save-fill' },
  { id: 'icon_font_3181', icon: 'security-fill' },
  { id: 'icon_font_3191', icon: 'Similarproducts-fill' },
  { id: 'icon_font_3201', icon: 'signboard-fill' },
  { id: 'icon_font_3211', icon: 'service-fill' },
  { id: 'icon_font_3221', icon: 'shuffling-banner-fill' },
  { id: 'icon_font_3231', icon: 'supplier-features-fill' },
  { id: 'icon_font_3241', icon: 'store-fill' },
  { id: 'icon_font_3251', icon: 'smile-fill' },
  { id: 'icon_font_3261', icon: 'success-fill' },
  { id: 'icon_font_3271', icon: 'sound-filling-fill' },
  { id: 'icon_font_3281', icon: 'sound-Mute1' },
  { id: 'icon_font_3291', icon: 'suspended-fill' },
  { id: 'icon_font_3301', icon: 'tool-fill' },
  { id: 'icon_font_3311', icon: 'task-management-fill' },
  { id: 'icon_font_3321', icon: 'unlock-fill' },
  { id: 'icon_font_3331', icon: 'trust-fill' },
  { id: 'icon_font_3341', icon: 'vip-fill' },
  { id: 'icon_font_3351', icon: 'set1' },
  { id: 'icon_font_3361', icon: 'Top-fill' },
  { id: 'icon_font_3371', icon: 'viewlarger1' },
  { id: 'icon_font_3381', icon: 'voice-fill' },
  { id: 'icon_font_3391', icon: 'warning-fill' },
  { id: 'icon_font_3401', icon: 'warehouse-fill' },
  { id: 'icon_font_3411', icon: 'zip-fill' },
  { id: 'icon_font_3421', icon: 'trade-assurance-fill' },
  { id: 'icon_font_3431', icon: 'vs-fill' },
  { id: 'icon_font_3441', icon: 'video1' },
  { id: 'icon_font_3451', icon: 'template-fill' },
  { id: 'icon_font_3461', icon: 'wallet1' },
  { id: 'icon_font_3471', icon: 'training1' },
  { id: 'icon_font_3481', icon: 'packing-labeling-fill' },
  { id: 'icon_font_3491', icon: 'Exportservices-fill' },
  { id: 'icon_font_3501', icon: 'brand-fill' },
  { id: 'icon_font_3511', icon: 'collection' },
  { id: 'icon_font_3521', icon: 'consumption-fill' },
  { id: 'icon_font_3531', icon: 'collection-fill' },
  { id: 'icon_font_3541', icon: 'brand' },
  { id: 'icon_font_3551', icon: 'rejected-order-fill' },
  { id: 'icon_font_3561', icon: 'homepage-ads-fill' },
  { id: 'icon_font_3571', icon: 'homepage-ads' },
  { id: 'icon_font_3581', icon: 'scenes-fill' },
  { id: 'icon_font_3591', icon: 'scenes' },
  { id: 'icon_font_3601', icon: 'similar-product-fill' },
  { id: 'icon_font_3611', icon: 'topraning-fill' },
  { id: 'icon_font_3621', icon: 'consumption' },
  { id: 'icon_font_3631', icon: 'topraning' },
  { id: 'icon_font_3641', icon: 'gold-supplier' },
  { id: 'icon_font_3651', icon: 'messagecenter-fill' },
  { id: 'icon_font_3661', icon: 'quick' },
  { id: 'icon_font_3671', icon: 'writing' },
  { id: 'icon_font_3681', icon: 'docjpge-fill' },
  { id: 'icon_font_3691', icon: 'jpge-fill' },
  { id: 'icon_font_3701', icon: 'gifjpge-fill' },
  { id: 'icon_font_3711', icon: 'bmpjpge-fill' },
  { id: 'icon_font_3721', icon: 'tifjpge-fill' },
  { id: 'icon_font_3731', icon: 'pngjpge-fill' },
  { id: 'icon_font_3741', icon: 'Hometextile' },
  { id: 'icon_font_3751', icon: 'home' },
  { id: 'icon_font_3761', icon: 'sendinquiry-fill' },
  { id: 'icon_font_3771', icon: 'comments-fill' },
  { id: 'icon_font_3781', icon: 'account-fill' },
  { id: 'icon_font_3791', icon: 'feed-logo-fill' },
  { id: 'icon_font_3801', icon: 'feed-logo' },
  { id: 'icon_font_3811', icon: 'home-fill' },
  { id: 'icon_font_3821', icon: 'add-select' },
  { id: 'icon_font_3831', icon: 'sami-select' },
  { id: 'icon_font_3841', icon: 'camera' },
  { id: 'icon_font_3851', icon: 'arrow-down' },
  { id: 'icon_font_3861', icon: 'account' },
  { id: 'icon_font_3871', icon: 'comments' },
  { id: 'icon_font_3881', icon: 'cart-Empty1' },
  { id: 'icon_font_3891', icon: 'favorites' },
  { id: 'icon_font_3901', icon: 'order' },
  { id: 'icon_font_3911', icon: 'search' },
  { id: 'icon_font_3921', icon: 'trade-assurance' },
  { id: 'icon_font_3931', icon: 'usercenter1' },
  { id: 'icon_font_3941', icon: 'tradingdata' }
]

export default {
  components: {},
  data() {
    return {
      iconList: icons
    }
  },
  computed: {},
  mounted() {},
  methods: {}
}

</script>
<style lang='scss' scoped>
.c-icon-grid {
  position: relative;
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(120px, 1fr));
  text-align: center;
  .c-icon-item {
    height: 80px;
    margin: 10px;
    cursor: pointer;
    color: #909399;
    font-size: 36px;
  }
  .c-icon-tip {
    transition: all 0.3s ease-in-out;
  }
  .c-icon-tip:hover {
    transform: scale(1.3);
  }
}
</style>
